apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth0-secret
  namespace: ecommerce
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: auth0-secret
    creationPolicy: Owner
  data:
    - secretKey: domain
      remoteRef: {key: auth0, property: domain}
    - secretKey: client_id
      remoteRef: {key: auth0, property: client_id}
    - secretKey: client_secret
      remoteRef: {key: auth0, property: client_secret}
    - secretKey: audience
      remoteRef: {key: auth0, property: audience}
