apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongo-secret
  namespace: ecommerce
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mongo-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef: {key: mongo, property: username}
    - secretKey: password
      remoteRef: {key: mongo, property: password}
    - secretKey: uri
      remoteRef: {key: mongo, property: uri}
