apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-secret
  namespace: ecommerce
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mysql-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef: {key: kv/data/mysql, property: username}
    - secretKey: password
      remoteRef: {key: kv/data/mysql, property: password}
    - secretKey: root_password
      remoteRef: {key: kv/data/mysql, property: root_password}
