apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-product-service
  namespace: ecommerce-staging
spec:
  action: pod-kill
  mode: one
  duration: "30s"
  selector:
    namespaces:
      - ecommerce-staging
    labelSelectors:
      app: product-service
  scheduler:
    cron: "@every 10m"
  dryRun: true
